- name: ensure docker installed
  package:
    name: docker
    state: present
  become: true

- name: Create a network
  docker_network:
    name: "{{network_name}}"

- name: set fact docker network
  set_fact:
    network: "{{network_name}}"